# Generated by Django 2.2.3 on 2019-07-22 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('proof', models.IntegerField()),
                ('previous_hash', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.TextField()),
                ('recipient', models.TextField()),
                ('value', models.FloatField()),
                ('executed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain', models.ManyToManyField(blank=True, to='adv_blockchain.Block')),
                ('current_transactions', models.ManyToManyField(blank=True, to='adv_blockchain.Transaction')),
            ],
        ),
        migrations.AddField(
            model_name='block',
            name='transactions',
            field=models.ManyToManyField(blank=True, to='adv_blockchain.Transaction'),
        ),
    ]
