# Generated by Django 2.2.3 on 2019-07-23 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adv_blockchain', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='value',
            new_name='amount',
        ),
        migrations.DeleteModel(
            name='Chain',
        ),
    ]
