# Generated by Django 2.2.3 on 2019-07-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adv_blockchain', '0002_auto_20190723_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChainDifficulty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.IntegerField()),
            ],
        ),
    ]
