# Generated by Django 2.2.4 on 2019-08-27 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adv_blockchain', '0003_chaindifficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='proof',
            field=models.BigIntegerField(),
        ),
    ]
