# Generated by Django 2.1.4 on 2018-12-30 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_player_cooldown'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DEFAULT_ITEM', max_length=20)),
                ('description', models.CharField(default='DEFAULT DESCRIPTION', max_length=200)),
                ('weight', models.IntegerField(default=1)),
                ('attributes', models.CharField(default='{}', max_length=1000)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventure.Player')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventure.Room')),
            ],
        ),
    ]
