# Generated by Django 2.1.4 on 2018-12-30 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0004_auto_20181230_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='aliases',
            field=models.CharField(default='[]', max_length=200),
        ),
    ]
