# Generated by Django 2.1.4 on 2018-12-30 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0005_item_aliases'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='value',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='aliases',
            field=models.CharField(default='', max_length=200),
        ),
    ]
