# Generated by Django 2.1.4 on 2018-12-30 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0006_auto_20181230_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='gold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='speed',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='player',
            name='strength',
            field=models.IntegerField(default=10),
        ),
    ]
