# Generated by Django 2.1.4 on 2019-01-14 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0010_room_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='itemtype',
            field=models.CharField(default='DEFAULT', max_length=20),
        ),
        migrations.AddField(
            model_name='player',
            name='bodywear',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='footwear',
            field=models.IntegerField(default=0),
        ),
    ]
