# Generated by Django 2.1.4 on 2019-01-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0011_auto_20190114_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='encumbrance',
            field=models.IntegerField(default=0),
        ),
    ]
