# Generated by Django 2.1.4 on 2019-01-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0012_player_encumbrance'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='description',
            field=models.CharField(default=' looks like an ordinary person.', max_length=140),
        ),
        migrations.AddField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
