# Generated by Django 2.1.4 on 2019-02-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0013_auto_20190130_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_pm',
            field=models.BooleanField(default=False),
        ),
    ]
