# Generated by Django 2.1.4 on 2019-02-03 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0014_player_is_pm'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
