# Generated by Django 2.1.4 on 2019-02-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0015_item_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='exp',
            field=models.IntegerField(default=0),
        ),
    ]
