# Generated by Django 2.1.4 on 2019-02-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0016_item_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='elevation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='terrain',
            field=models.CharField(default='NORMAL', max_length=32),
        ),
    ]
