# Generated by Django 2.1.4 on 2019-02-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0017_auto_20190207_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='can_fly',
            field=models.BooleanField(default=False),
        ),
    ]
