# Generated by Django 2.1.4 on 2019-02-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0018_player_can_fly'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='can_dash',
            field=models.BooleanField(default=False),
        ),
    ]
