# Generated by Django 2.2.3 on 2019-08-01 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0023_player_has_mined'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='catchup_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
