# Generated by Django 2.2.3 on 2019-08-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0024_group_catchup_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='can_carry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='carried_item',
            field=models.IntegerField(default=0),
        ),
    ]
