# Generated by Django 2.2.3 on 2019-10-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0025_auto_20190829_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='mining_room',
            field=models.IntegerField(default=0),
        ),
    ]
