# Generated by Django 2.2.3 on 2019-10-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0026_player_mining_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='mining_puzzle',
            field=models.TextField(default=''),
        ),
    ]
