# Generated by Django 2.2.3 on 2019-11-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0028_auto_20191021_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='can_warp',
            field=models.BooleanField(default=False),
        ),
    ]
