# Generated by Django 2.2.3 on 2019-11-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0029_player_can_warp'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='snitches',
            field=models.IntegerField(default=0),
        ),
    ]
