# Generated by Django 3.0.2 on 2020-02-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0031_auto_20200106_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='can_recall',
            field=models.BooleanField(default=False),
        ),
    ]
