# Generated by Django 3.0.2 on 2020-02-25 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0032_player_can_recall'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='has_clear_well',
            field=models.BooleanField(default=False),
        ),
    ]
