# Generated by Django 3.0.2 on 2020-02-29 15:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0033_group_has_clear_well'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='donut_boost',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
