# Generated by Django 3.0.2 on 2020-03-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0034_player_donut_boost'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='move_log',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='player',
            name='num_moves',
            field=models.IntegerField(default=0),
        ),
    ]
