# Generated by Django 3.0.2 on 2020-03-29 18:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0035_auto_20200328_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='pizza_power',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
